---
- name: ApaChe
  hosts: 127.0.0.1
  become: yes
  gather_facts: yes
  tasks:
    - name: install ApaChe
      apt:
        name: apache2
        state: present
    - name: Insert
      copy:
        content: |
          <html>
          <body>
          <h1>INFO</h1>
          <p>CPU: {{ ansible_processor }}</p>
          <p>ram: {{ ansible_memtotal_mb }} MB</p>
          <p>IP: {{ ansible_default_ipv4.address }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'       
       
    - name: restart ApaChe
      service:
        name: apache2
        state: restarted
    - name: firewal
      firewalld:
        port: 80
        permanent: yes
        state: enabled
    - name: stert ApaChe
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://127.0.0.1
    - name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
      uri:
        url: http://127.0.0.1
        return_content: yes
      register: this
      failed_when: "'AWESOME' not in this.content"