stages:          # List of stages for jobs, and their order of execution
  - build
  - test
tags:
  - netology

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - sudo mkdir /opt/build
    - sudo touch /opt/build/info.txt

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - cat /opt/build