---
- name: unarchive module
  hosts: all
  tasks:
    - name: Create Dir
      file:
        path: /tmp/unpack/
        state: directory
    - name: download
      get_url:
        url: https://downloads.apache.org/kafka/3.7.0/kafka_2.12-3.7.0.tgz
        dest: /tmp/unpack/kafka-3.7.0-src.tgz
    - name: Unpack 
      unarchive:
        src: /tmp/unpack/kafka-3.7.0-src.tgz
        dest: /tmp/unpack/
        remote_src: yes